server:
  port: 9090
spring:  
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://reddit.com
          predicates :
          - Path=/test123
        - id: another_route
          uri: https://reddit.cm
          predicates :
          - Path=/another
# "*" exposure enables actuator access, eg localhost:xxxx/actuator/gateway/routes
# especially important in order to expose the /refresh actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"