server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: reddit_route
          predicates:
            - Path=/reddit
          uri: https://reddit.com
        # - id: insta_route
        #   uri: ${rewrite.backend.uri:https://instagram.com}
        #   predicates:
        #   - Path=/instagram/**
        #   filters:
        #   - RewritePath=/instagram/(?<username>.*),/$\{username}
# "*" exposure enables actuator access, eg localhost:xxxx/actuator/gateway/routes
# especially important in order to expose the /refresh actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"
