server:
  port: 9090
spring:  
  cloud:
    gateway:
      routes:
        - id: kanoogi_route
          uri: https://main.kanoogi.com/
          predicates :
          - Path=/kanoogi
        - id: insta_route
          uri: https://instagram.com
          predicates: 
          - Path=/instagram
          filters:
          - RewritePath=/christaylorpottery
# "*" exposure enables actuator access, eg localhost:xxxx/actuator/gateway/routes
# especially important in order to expose the /refresh actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"